version: '3.0'
services:
  mysql8:
    image: mysql:8.0
    container_name: mysql8
    privileged: true
    ports:
      - "3306:3306"
    #      - "80:3306"
    volumes:
    #      - db_data:/var/lib/mysql
      - ./script/mysql/:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: ykt_backup
      MYSQL_PASSWORD: Ykt_2020_new

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 12379:2379
