apiVersion: v1
# 这个指我k8s有哪些volume
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  storageClassName: webook
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook"